name: Compile and Test theKeyboardEditor
on:
  push:
    branches:
      - master
      - github-actions
jobs:
  linux-web-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: 'recursive'
    
      - name: Compile for Web
        run: node vendor/Kha/make html5 
      
      - name: Install dependencies for Linux compilation
        run: sudo apt install -y make g++ libxinerama-dev libxrandr-dev libasound2-dev libxi-dev mesa-common-dev libgl-dev libxcursor-dev libvulkan-dev libudev-dev
      
      - name: Compile for Linux
        run: node vendor/Kha/make --compile -g opengl

      - name: Deploy web version
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/html5/ # The folder the action should deploy.
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Compile for Windows
        run: node vendor/Kha/make -g direct3d12 -v vs2017
  macos-build: 
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Compile for macOS
        run: node vendor/Kha/make --compile
